project:
  type: website

website:
  title: "IS415-Wan Shen"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - href: "https://github.com/wanshen123/IS415-GAA"
        icon: "bi bi-github"
  #sidebar:
    #style: "docked"
    #alignment: right
    #search: true
    #contents:
      #- section: "Categories"
        
      #- section: "Hands-On Exercise"
        #contents: 
          #- Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

