project:
  type: website

website:
  title: "IS415-Wan Shen"
  navbar:
    left:
      #- href: "index.qmd"
        #icon: "bi bi-house-door-fill"
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
    right:
      - href: "https://github.com/wanshen123/IS415-GAA"
        icon: "bi bi-github"
  #sidebar:
    #style: "docked"
    #alignment: right
    #search: true
    #contents:
      #- section: "Categories"
        
      #- section: "Hands-On Exercise"
        #contents: 
          #- Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

