project:
  type: website

website:
  title: "IS415-Wan Shen"
  navbar:
    left:
      #- href: "index.qmd"
        #icon: "bi bi-house-door-fill"
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3A"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3B"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "Hands-on Exercise 3C"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03c.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5A"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
          - text: "Hands-on Exercise 5B"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 6"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 7"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "In-class Exercise 8"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    right:
      - href: "https://github.com/wanshen123/IS415-GAA"
        icon: "bi bi-github"
  #sidebar:
    #style: "docked"
    #alignment: right
    #search: true
    #contents:
      #- section: "Categories"
        
      #- section: "Hands-On Exercise"
        #contents: 
          #- Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

