---
title: "In-class Exercise 4"
description: "Working with Geographically Weighted Summary Statistics (GWSS)"
execute: 
  warning: false
  eval: true
  echo: true
# date: "`r Sys.Date()`"
date: 01/29/2024
date-format: "D MMM, YYYY" 
author: 
  - Wan Shen
sidebar: false
title-block-banner: true
categories:
  - In-Class Exercise
title-block-categories: false
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr, GWmodel)
```

```{r}
hunan <- st_read(dsn = "../../data/geospatial", 
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("../../data/aspatial/Hunan_2012.csv")
```

```{r}
hunan <- left_join(hunan,hunan2012)%>%
    select(1:4, 7, 15)
```

```{r}
#| fig-width: 8
#| fig-height: 6
basemap <- tm_shape(hunan) +
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

gdppc <- qtm(hunan, "GDPPC")
tmap_arrange(basemap, gdppc, asp=1, ncol=2)
```

```{r}
wm_q <- poly2nb(hunan, queen=TRUE)
summary(wm_q)
```

```{r}
longitude <- map_dbl(hunan$geometry,~st_centroid(.x)[[1]])
```

```{r}
latitude <- map_dbl(hunan$geometry,~st_centroid(.x)[[2]])
```

```{r}
coords <- cbind(longitude, latitude)
```

```{r}
k1 <- knn2nb(knearneigh(coords))
```

```{r}
k1dists <- unlist(nbdists(k1, coords, longlat = TRUE))
```

```{r}
#| fig-width: 8
#| fig-height: 6
plot(hunan$geometry, border="lightgrey")
plot(wm_q, coords, pch=19, cex=0.6, add=TRUE, col="red")
```

## Working with Geographically Weighted Summary Statistics (GWSS)

```{r}
hunan_sp <- hunan %>%
  as_Spatial()
```

```{r}
#Adaptive = True, bw = 6 Neighbors. Adaptive = False, bw = 62 KM.
gwstat <- gwss(data = hunan_sp,
               vars = "GDPPC",
               bw = 6,
               kernel = "bisquare",
               adaptive = TRUE,
               longlat = T)
```

```{r}

```